# Generated by Django 2.0 on 2020-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoLabel', '0003_auto_20200429_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodb',
            name='firstFrame',
            field=models.TextField(default=''),
        ),
    ]
